[build]
  command = "pip install -r requirements.txt && python app.py"
  command = "gunicorn -w 4 -b 0.0.0.0:$PORT app:app"

[functions]
  directory = "serverless/"

[build.environment]
  FLASK_ENV = "production"
  FLASK_APP = "app.py"

[dev]
  publish = "serverless/"

[[redirects]]
  from = "/*"
  to = "/login.html"
  status = 200
