[build]
  command = "pip install -r requirements.txt && uwsgi uwsgi.ini"
  
[uwsgi]
  module = app:app
  socket = :$(PORT)
  protocol = http

[functions]
  directory = "serverless/"
  
[build.environment]
  FLASK_ENV = "production"
  FLASK_APP = "app.py"

[dev]
  publish = "serverless/"

[[redirects]]
  from = "/*"
  to = "/login.html"
  status = 200
