[build]
  command = "pip install -r requirements.txt && python app.py"
  functions = "serverless/"

[build.environment]
  FLASK_ENV = "production"
  FLASK_APP = "app.py"

[dev]
  publish = "serverless/"

[[redirects]]
  from = "/*"
  to = "/login.html"
  status = 200
